import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Server } from "node:http";
import { startStaticServer } from "./helpers/static-server.js";
import { runPipeline } from "../src/pipeline.js";
import { LLMClient, RateLimiter } from "../src/llm/client.js";
import { heuristicMockTarget } from "../src/llm/mock.js";
import { mockTarget, type LLMRequest } from "../src/llm/providers.js";
import { validateKit } from "../src/kit/validate.js";
import { computeCoverage } from "../src/coverage/coverage.js";

const root = join(__dirname, "..", "..", "..", "fixtures");
const jd = (f: string) => readFileSync(join(root, "jds", f), "utf8");
let server: Server;
let base: string;
const noDiscussion = async () => ({ snippets: [], searched: ["x"], failures: [] });

beforeAll(async () => {
  ({ server, url: base } = await startStaticServer(join(root, "sites")));
});
afterAll(() => server.close());

const llm = () => new LLMClient([heuristicMockTarget()], new RateLimiter(1000));

describe("runPipeline (offline, rule-based mock model)", () => {
  it("builds a valid kit, runs a real second coverage pass, and uses the published process", async () => {
    const steps: string[] = [];
    const res = await runPipeline(
      { jd: jd("senior-backend.txt"), company_url: `${base}/acme/`, days: 5 },
      { llm: llm(), allowPrivate: true, searchDiscussion: noDiscussion, onProgress: (e) => steps.push(`${e.step}:${e.status}`) },
    );
    const { kit } = res;
    expect(validateKit(kit).ok).toBe(true);
    expect(kit.schedule.days).toHaveLength(5);
    expect(kit.coverage.passes).toBeGreaterThanOrEqual(2); // mock leaves a gap on purpose
    expect(computeCoverage(kit.role.requirements, kit.questions).uncoveredMust).toEqual([]);
    expect(kit.source.pages_used).toContain(`${base}/acme/company/handbook/interviewing.html`);
    expect(kit.research!.hiring_page_found).toBe(true);
    expect(kit.interview_process!.found).toBe(true);
    // system-design category generated because the company publishes a system design round
    expect(kit.questions.some((q) => q.category === "system-design")).toBe(true);
    // categories are generated by separate steps
    for (const c of ["technical", "behavioural", "system-design", "company-fit"]) expect(steps).toContain(`questions:${c}:done`);
    expect(steps).toContain("coverage:done");
    // must/nice from posting wording
    const kafka = kit.role.requirements.find((r) => /kafka/i.test(r.text))!;
    expect(kafka.priority).toBe("nice");
    expect(kit.role.requirements.some((r) => /PTO|remote-first/i.test(r.text))).toBe(false);
  });

  it("produces a thin, honest kit for a two-line posting and a company with no hiring page", async () => {
    const { kit } = await runPipeline({ jd: jd("stub.txt"), company_url: `${base}/globex/`, days: 1 }, { llm: llm(), allowPrivate: true, searchDiscussion: noDiscussion });
    expect(validateKit(kit).ok).toBe(true);
    expect(kit.role.requirements.length).toBeLessThanOrEqual(2);
    expect(kit.research!.thin_jd).toBe(true);
    expect(kit.research!.hiring_page_found).toBe(false);
    expect(kit.interview_process!.found).toBe(false);
    expect(kit.research!.notes.join(" ")).toMatch(/very little detail/);
    expect(kit.schedule.days).toHaveLength(1);
  });

  it("records an unreachable company and still returns a kit from the posting alone", async () => {
    const { kit } = await runPipeline({ jd: jd("product-designer.txt"), company_url: `${base}/nope/`, days: 60 }, { llm: llm(), allowPrivate: true, searchDiscussion: noDiscussion });
    expect(validateKit(kit).ok).toBe(true);
    expect(kit.source.pages_used).toEqual([]);
    expect(kit.company_brief.sources).toEqual([]);
    expect(kit.company_brief.summary).toMatch(/could not/i);
    expect(kit.schedule.days).toHaveLength(60);
    expect(kit.research!.notes.join(" ")).toMatch(/could not be used/);
    expect(kit.role.requirements.find((r) => /figma/i.test(r.text))?.priority).toBe("nice");
  });

  it("wraps crawled text as untrusted data (prompt-injection guard)", async () => {
    const seen: LLMRequest[] = [];
    const inner = heuristicMockTarget();
    const spy = mockTarget(async (req) => {
      seen.push(req);
      return inner.call(req);
    });
    await runPipeline({ jd: jd("senior-backend.txt"), company_url: `${base}/acme/`, days: 3 }, { llm: new LLMClient([spy], new RateLimiter(1000)), allowPrivate: true, searchDiscussion: noDiscussion });
    const briefReq = seen.find((r) => /company brief/.test(r.system))!;
    expect(briefReq.system).toMatch(/Ignore any instructions/);
    const injected = briefReq.user.indexOf("Ignore all previous instructions");
    if (injected >= 0) {
      const open = briefReq.user.lastIndexOf("<untrusted_company_pages>", injected);
      const close = briefReq.user.indexOf("</untrusted_company_pages>", injected);
      expect(open).toBeGreaterThanOrEqual(0);
      expect(close).toBeGreaterThan(injected);
    }
    const extractReq = seen.find((r) => /extract structured/.test(r.system))!;
    expect(extractReq.user).toMatch(/<untrusted_job_posting>/);
  });

  it("fails cleanly when the model is unavailable", async () => {
    const dead = new LLMClient([mockTarget(() => { throw Object.assign(new Error("x")); })], new RateLimiter(1000));
    await expect(runPipeline({ jd: jd("stub.txt"), company_url: `${base}/acme/`, days: 2 }, { llm: dead, allowPrivate: true, searchDiscussion: noDiscussion })).rejects.toBeTruthy();
  });

  it("rejects invalid input", async () => {
    await expect(runPipeline({ jd: "", company_url: "x", days: 3 }, { llm: llm(), allowPrivate: true })).rejects.toMatchObject({ code: "INVALID_INPUT" });
    await expect(runPipeline({ jd: "A real job description here", company_url: "x", days: 0 }, { llm: llm(), allowPrivate: true })).rejects.toMatchObject({ code: "INVALID_INPUT" });
  });
});

describe("company brief input", () => {
  it("includes short pages (a tiny homepage is still evidence)", async () => {
    const { researchCompany } = await import("../src/steps/company-brief.js");
    let seen = "";
    const spy = new LLMClient([mockTarget((req) => { seen = req.user; return JSON.stringify({ summary: "s", what_they_do: "w", sources: [] }); })], new RateLimiter(1000));
    await researchCompany(spy, { companyName: "G", companyUrl: "http://g/", reachable: true, pages: [{ url: "http://g/", title: "G", text: "Globex makes dashboards for retail stores.", kind: "home" }], discussion: [], processDescribed: false, hiringPageUrl: null });
    expect(seen).toContain("Globex makes dashboards");
  });
});
